# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20170626_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='use_type',
            new_name='user_type',
        ),
    ]
