# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_video_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
