# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20170620_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('thumbnails', models.ImageField(upload_to='youtube')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
