# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_video'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='video',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
