# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 03:37
from __future__ import unicode_literals

from django.db import migrations
import utils.fields.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_video'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='video',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=utils.fields.custom_imagefield.CustomImageField(blank=True, null=True, upload_to='', verbose_name='Video'),
        ),
    ]
