# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20170627_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnails',
            field=models.CharField(max_length=200),
        ),
    ]
